### ISSUE TITLE
[JSON-LD Vocabulary]: proper definitions for JSON-LD vocabulary

### ISSUE THREAD

**Issue by kshychko** [jargon-sh/issues#7]
Current JSON-LD vocabulary file require the following moments to be fixed:

- [ ] For code list values `rdf:value` is used instead of `ns:Name` #8 
- [ ] Imported code lists are included into the vocabulary correctly #9
- [ ] `@context` includes schema.org URI #10
- [ ] vocabulary URI is configurable #11

**Comment by colugo** [comment]
I think the design for these has moved on, so I'm closing this
